src/Entity/Accompagnement.php
<?php

namespace App\Entity;

use App\Repository\AccompagnementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AccompagnementRepository::class)]
class Accompagnement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Column( name:"task_id")]
    private ?Tasks $task = null;

    #[ORM\Column]
    private ?bool $is_accepted = null;

    #[ORM\ManyToOne(inversedBy: 'accompagnements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;


    #[ORM\ManyToOne(inversedBy: 'accompagnements_pro')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_pro = null;




    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }







    public function getTask(): ?tasks
    {
        return $this->task;
    }

    public function setTask(tasks $task_id): self
    {
        $this->task= $task_id;

        return $this;
    }

    public function isIsAccepted(): ?bool
    {
        return $this->is_accepted;
    }

    public function setIsAccepted(bool $is_accepted): self
    {
        $this->is_accepted = $is_accepted;

        return $this;
    }

    public function getUserPro(): ?User
    {
        return $this->user_pro;
    }

    public function setUserPro(?User $user_pro): self
    {
        $this->user_pro = $user_pro;

        return $this;
    }
}

src/Form/AccompagnementType.php
<?php

namespace App\Form;

use App\Entity\Accompagnement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AccompagnementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('is_accepted')
            ->add('user')
            ->add('task')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Accompagnement::class,
        ]);
    }
}

src/Controller/AccompagnementController.php
<?php

namespace App\Controller;

use App\Entity\Accompagnement;
use App\Form\Accompagnement1Type;
use App\Repository\AccompagnementRepository;
use App\Repository\TasksRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/accompagnement')]
class AccompagnementController extends AbstractController
{
    #[Route('/', name: 'app_accompagnement_index', methods: ['GET'])]
    public function index(AccompagnementRepository $accompagnementRepository): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        return $this->render('accompagnement/index.html.twig', [
            'accompagnements' => $accompagnementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_accompagnement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AccompagnementRepository $accompagnementRepository): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $accompagnement = new Accompagnement();
        $form = $this->createForm(Accompagnement1Type::class, $accompagnement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $accompagnementRepository->save($accompagnement, true);

            return $this->redirectToRoute('app_accompagnement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('accompagnement/new.html.twig', [
            'accompagnement' => $accompagnement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_accompagnement_show', methods: ['GET'])]
    public function show(Accompagnement $accompagnement): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        return $this->render('accompagnement/show.html.twig', [
            'accompagnement' => $accompagnement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_accompagnement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Accompagnement $accompagnement, AccompagnementRepository $accompagnementRepository): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $form = $this->createForm(Accompagnement1Type::class, $accompagnement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $accompagnementRepository->save($accompagnement, true);

            return $this->redirectToRoute('app_accompagnement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('accompagnement/edit_admin.html.twig', [
            'accompagnement' => $accompagnement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_accompagnement_delete', methods: ['POST'])]
    public function delete(Request $request, Accompagnement $accompagnement, AccompagnementRepository $accompagnementRepository): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        if ($this->isCsrfTokenValid('delete'.$accompagnement->getId(), $request->request->get('_token'))) {
            $accompagnementRepository->remove($accompagnement, true);
        }

        return $this->redirectToRoute('app_accompagnement_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/send_request/{id}/{t}', name: 'app_accompagnemet_send_request', methods: ['GET','POST'])]
    public function add_acoompagnement( $id,$t, Request $request, UserRepository $userRepository,TasksRepository $tasksRepository, AccompagnementRepository $accompagnementRepository): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        //CREATE AN accompagnement et apres update user and add the id key inside the user
        $accompagnement = new Accompagnement();
        $user_prof=$userRepository->find($id);
        $user=$userRepository->find($id);
        if (!$user_prof) {
            throw $this->createNotFoundException('Unable to find Preisliste entity user profes.');
        }



        $accompagnement->setUser($user);
        $accompagnement->setUserPro($user_prof);
        $accompagnement->setTask($tasksRepository->find($t));
        $accompagnement->setIsAccepted(false);
        $accompagnementRepository->save($accompagnement, true);

        // hétha té5thou min session badlouu
     /*   $user = $userRepository->find(888);
        if (!$user) {
            throw $this->createNotFoundException('Unable to find Preisliste entity user 3adi.');
        }*/

        //$user->setAccompagnement($accompagnement);

        //$userRepository->save($user, true);
        dd($user);
        dd($accompagnement);
        //return new Response("some content");

    }
    //linna delete accompagnement


    //select il accompagnement of user 3addiyin
    #[Route('/user/{id}', name: 'app_accompagnement_user', methods: ['GET'])]
    public function get_tasks(AccompagnementRepository $accompagnementRepository,$id): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $tasks=[];
            $accompagnement_list = $accompagnementRepository->findBy(["user"=> ["user_id" => $id]]);
            foreach ($accompagnement_list as $accompagnement){
                array_push($tasks,$accompagnement->getTask());
            }
            dd($tasks);
     /*   return $this->render('accompagnement/show.html.twig', [
            'accompagnement' => $accompagnement,
        ]);
    }
    #[Route('/enable/{id_user}/{id_userP}', name: 'app_accompagnement_enable', methods: ['GET'])]
    public function accompagnemen_enable($id_user,$id_userP,AccompagnementRepository $accompagnementRepository): Response
    {           $task_list=[];
        $accompagnement_list = $accompagnementRepository->findBy(["user"=>["user_id" => $id_user],"user_pro"=> ["user_pro_id" =>$id_userP]]);
       foreach ($accompagnement_list as $accompagnement){
           //$task_list[]=$accompagnement->getTask();
           $accompagnement->setIsAccepted(true);
           $accompagnementRepository->save($accompagnement,true);
       }
        dd($task_list);
        /*   return $this->render('accompagnement/show.html.twig', [
               'accompagnement' => $accompagnement,
           ]);*/
    }
    //select il accompagnement of pro user


}

templates/accompagnement/_delete_form.html.twig
<form method="post" action="{{ path('app_accompagnement_delete', {'id': accompagnement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ accompagnement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/accompagnement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/accompagnement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Accompagnement{% endblock %}

{% block body %}


    <h1>Edit Accompagnement</h1>

    {{ include('accompagnement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_accompagnement_index') }}">back to list</a>

    {{ include('accompagnement/_delete_form.html.twig') }}
{% endblock %}

templates/accompagnement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accompagnement index
{% endblock %}

{% block body %}
    <h1>Accompagnement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Is_accepted</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for accompagnement in accompagnements %}
            <tr>
                <td>{{ accompagnement.id }}</td>
                <td>{{ accompagnement.isAccepted ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_accompagnement_show', {'id': accompagnement.id}) }}">show</a>
                    <a href="{{ path('app_accompagnement_edit', {'id': accompagnement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_accompagnement_new') }}">Create new</a>
{% endblock %}

templates/accompagnement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Accompagnement{% endblock %}

{% block body %}


    <h1>Create new Accompagnement</h1>

    {{ include('accompagnement/_form.html.twig') }}

    <a href="{{ path('app_accompagnement_index') }}">back to list</a>
{% endblock %}

templates/accompagnement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accompagnement
{% endblock %}

{% block body %}

    <h1>Accompagnement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ accompagnement.id }}</td>
            </tr>
            <tr>
                <th>Is_accepted</th>
                <td>{{ accompagnement.isAccepted ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_accompagnement_index') }}">back to list</a>

    <a href="{{ path('app_accompagnement_edit', {'id': accompagnement.id}) }}">edit</a>

    {{ include('accompagnement/_delete_form.html.twig') }}
{% endblock %}