src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 5,
        max: 50,
        minMessage: 'minumum 5 caratéres',
        maxMessage: 'ùaximum 50 caracteres',
    )]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $time = null;

    #[ORM\Column]
    private ?bool $is_complete = null;

    #[ORM\ManyToOne(inversedBy: 'list_items')]
    #[Assert\NotBlank]
    private Tasks $tasks ;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function isIsComplete(): ?bool
    {
        return $this->is_complete;
    }

    public function setIsComplete(bool $is_complete): self
    {
        $this->is_complete = $is_complete;

        return $this;
    }

    public function getTasks(): ?Tasks
    {
        return $this->tasks;
    }

    public function setTasks(?Tasks $tasks): self
    {
        $this->tasks = $tasks;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Form/ItemType.php
<?php

namespace App\Form;

use App\Entity\Item;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('time')
            ->add('is_complete')
            ->add('photo', FileType::class, [
                'label' => 'Picture (JPEG, PNG or GIF file)',
                'mapped' => false,
                'required' => false,
            ])
            ->add('tasks')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {

        $resolver->setDefaults([
            'data_class' => Item::class,
        ]);
    }
}

src/Controller/ItemController.php
<?php

namespace App\Controller;

use App\Entity\Item;
use App\Entity\Tasks;
use App\Form\ItemType;
use App\Repository\ItemRepository;
use App\Repository\TasksRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/item')]
class ItemController extends AbstractController
{
    #[Route('/', name: 'app_item_index', methods: ['GET'])]
    public function index(ItemRepository $itemRepository): Response
    {
        return $this->render('item/index.html.twig', [
            'items' => $itemRepository->findAll(),
        ]);
    }


    #[Route('/task/{id}', name: 'app_task_items', methods: ['GET'])]
    public function find_items(ItemRepository $itemRepository ,TasksRepository $tasksRepository,$id): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $items=$itemRepository->findBy(['tasks'=>$id]);
        $task =$tasksRepository->findOneBy(['id'=>$id]);
        //dd($items);
        return $this->render('item/index.html.twig', [
            'items' =>$items ,'task'=>$task
        ]);




    }

    #[Route('admin/task/{id}', name: 'app_task_items_admin', methods: ['GET']), IsGranted('ROLE_ADMIN')]
    public function find_items_admin(ItemRepository $itemRepository ,TasksRepository $tasksRepository,$id): Response
    {       $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $items = $itemRepository->findBy(['tasks' => $id]);
        $task = $tasksRepository->findOneBy(['id' => $id]);
        //dd($items);
        return $this->render('item/index_admin.html.twig', [
            'items' => $items, 'task' => $task
        ]);
    }


    #[Route('/new', name: 'app_item_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ItemRepository $itemRepository,SluggerInterface $slugger,TasksRepository $tasksRepository): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $item = new Item();
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task=$form->get('tasks')->getData();
            $id_task=$task->getId();

            $pictureFile = $form->get('photo')->getData();
            if ($pictureFile) {
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();

                try {
                    $pictureFile->move(
                        $this->getParameter('users_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // handle exception
                }
                $item->setPhoto($newFilename);
            }
            $itemRepository->save($item, true);

            return $this->redirect('http://127.0.0.1:8000/item/task/'.$id_task);
        }

        return $this->renderForm('item/new.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_item_show', methods: ['GET'])]
    public function show(Item $item): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        return $this->render('item/show.html.twig', [
            'item' => $item,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_item_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Item $item, ItemRepository $itemRepository,SluggerInterface $slugger,$id): Response
    {$user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        $form = $this->createForm(ItemType::class, $item);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $task_id =$form->get('tasks')->getData()->getId();

            $pictureFile = $form->get('photo')->getData();
            if ($pictureFile) {
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();

                try {
                    $pictureFile->move(
                        $this->getParameter('users_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // handle exception
                }
                $item->setPhoto($newFilename);
            }


            $itemRepository->save($item, true);

            return $this->redirect('http://127.0.0.1:8000/item/task/'.$task_id);
        }

        return $this->renderForm('item/edit_admin.html.twig', [
            'item' => $item,
            'form' => $form,

        ]);
    }

    #[Route('/{id}', name: 'app_item_delete', methods: ['POST','GET'])]
    public function delete(Request $request, Item $item, ItemRepository $itemRepository): Response
    {       $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        if ($this->isCsrfTokenValid('delete'.$item->getId(), $request->request->get('_token'))) {
            $itemRepository->remove($item, true);
        }
        $task_id=$item->getTasks()->getId();
        return $this->redirect('http://127.0.0.1:8000/item/task/'.$task_id);
    }
}

templates/item/_delete_form.html.twig
<form method="post" action="{{ path('app_item_delete', {'id': item.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
    <button class="btn">Delete</button>
</form>

templates/item/_form.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<section class="contact-layout1 pt-0 mt--100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-panel d-flex flex-wrap">
                    <div class="contact-panel__form" >
                        <div class="col">
                            <div class="col-sm-12">   <p class="contact-panel__desc mb-30">
                                </p>
                                <p class="contact-panel__desc mb-30">
                                </p>   <p class="contact-panel__desc mb-30">
                                </p>
                                <h4 class="contact-panel__title">votre item </h4>
                                <p class="contact-panel__desc mb-30">
                                </p>
                            </div>
                            <div class="">
                                <div class="">
                                    {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
                                    {{ form_label(form.titre,"titre") }}
                                    {{ form_widget(form.titre,{'attr':{'class':'form-control'}}) }}
                                    {% if form_errors(form.titre) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.titre) }}
                                        </div>
                                    {% endif %}

                                </div>
                            </div><!-- /.col-lg-6 -->
                            <div class="">

                                <div class="">

                                    {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
                                    {{ form_label(form.time,"Temps") }}
                                    {{ form_widget(form.time,{'attr':{'class':''}}) }}
                                    {% if form_errors(form.time) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.time) }}
                                        </div>
                                    {% endif %}

                                </div>
                            </div><!-- /.col-lg-6 -->

                            <div class="col-sm-6 col-md-6 col-lg-6">
                                <div class="form-group">
                                    {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
                                    {{ form_label(form.is_complete,"compléter") }}
                                    {{ form_widget(form.is_complete,{'attr':{'class':'form-group-date'}}) }}
                                    {% if form_errors(form.is_complete) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.is_complete) }}
                                        </div>
                                    {% endif %}

                                </div>
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                <div class="form-group">
                                    {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
                                    {{ form_label(form.tasks,"inserer taske") }}
                                    {{ form_widget(form.tasks) }}
                                    {{ form_errors(form.tasks,{'attr':{'class':'alert alert-danger'}}) }}
                                    {% if form_errors(form.tasks) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.tasks) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
                                    {{ form_label(form.photo,"inserer image") }}
                                    {{ form_widget(form.photo) }}
                                    {% if form_errors(form.photo) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.photo) }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>

                            <!-- /.col-lg-6 -->
                            {#    <div class="col-sm-6 col-md-6 col-lg-6">
                                <div class="form-group">
                                    <i class="icon-news form-group-icon"></i>
                                    <select class="form-control">
                                        <option value="0">Subject</option>
                                        <option value="1">Subject 1</option>
                                        <option value="2">Subject 1</option>
                                    </select>
                                </div>
                            </div><!-- /.col-lg-6 -->#}
                            <div class="col-12">
                                <button class="btn">{{ button_label|default('enregister') }}</button>
                                {{ form_row(form._token) }}

                                <div class="contact-result"></div>
                            </div><!-- /.col-lg-12 -->
                        </div><!-- /.row -->
                    </div>
                    <div
                            class="contact-panel__info d-flex flex-column justify-content-between t">
                        <div class="bg-img"><img src="{{ asset("massets/img.png") }}" alt="banner"></div>
                        <div>
                            <h4 class="contact-panel__title color-black"></h4>

                        </div>
                        <div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/item/download.html.twig
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>pdf item</title>
    <link rel="stylesheet" href="{{asset("pdf_css_item/style.css") }}" media="all" />
    <style>.clearfix:after {
            content: "";
            display: table;
            clear: both;
        }

        a {
            color: #5D6975;
            text-decoration: underline;
        }

        body {
            position: relative;
            height: 29.7cm;
            margin: 0 auto;
            color: #001028;
            background: #FFFFFF;
            font-family: Arial, sans-serif;
            font-size: 12px;
            font-family: Arial;
        }

        header {
            padding: 10px 0;
            margin-bottom: 30px;
        }

        #logo {
            text-align: center;
            margin-bottom: 10px;
        }

        #logo img {
            width: 90px;
        }

        h1 {
            border-top: 1px solid  #5D6975;
            border-bottom: 1px solid  #5D6975;
            color: #5D6975;
            font-size: 2.4em;
            line-height: 1.4em;
            font-weight: normal;
            text-align: center;
            margin: 0 0 20px 0;
            background: url(dimension.png);
        }

        #project {
            float: left;
        }

        #project span {
            color: #5D6975;
            text-align: right;
            width: 52px;
            margin-right: 10px;
            display: inline-block;
            font-size: 0.8em;
        }

        #company {
            float: right;
            text-align: right;
        }

        #project div,
        #company div {
            white-space: nowrap;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            margin-bottom: 20px;
        }

        table tr:nth-child(2n-1) td {
            background: #F5F5F5;
        }

        table th,
        table td {
            text-align: center;
        }

        table th {
            padding: 5px 20px;
            color: #5D6975;
            border-bottom: 1px solid #C1CED9;
            white-space: nowrap;
            font-weight: normal;
        }

        table .service,
        table .desc {
            text-align: left;
        }

        table td {
            padding: 20px;
            text-align: right;
        }

        table td.service,
        table td.desc {
            vertical-align: top;
        }

        table td.unit,
        table td.qty,
        table td.total {
            font-size: 1.2em;
        }

        table td.grand {
            border-top: 1px solid #5D6975;;
        }

        #notices .notice {
            color: #5D6975;
            font-size: 1.2em;
        }

        footer {
            color: #5D6975;
            width: 100%;
            height: 30px;
            position: absolute;
            bottom: 0;
            border-top: 1px solid #C1CED9;
            padding: 8px 0;
            text-align: center;
        }</style>
</head>
<body>
<header class="clearfix">
    <div id="logo">
{#
        <img src="{{ asset('img/helpex.png')}} ">
#}
    </div>
    <h1>INVOICE : liste des items</h1>
    <div id="company" class="clearfix">
        <div>Company Name:helpex</div>
        <div>ESprit Ecole d'ingenieurs,<br /> AZ 85004, Tunis</div>
        <div>(602) 519-0450</div>
        <div><a href="mailto:company@example.com">Esprit@esprit.tn</a></div>
    </div>
    <div id="project">
        <div><span>PROJECT</span> Website development</div>
        <div><span>CLIENT</span> John Doe</div>
        <div><span>ADDRESS</span> 796 Silver Harbour, TX 79273, US</div>
        <div><span>EMAIL</span> <a href="mailto:john@example.com">john@gmail.com</a></div>
        <div><span>DATE</span> MAY 17, 2023</div>
        <div><span>DUE DATE</span> MAY 28, 2023</div>
    </div>
</header>
<main>
    <table>
        <thead>
        <tr>
            <th class="service">SERVICE</th>
            <th class="desc">DESCRIPTION</th>
            <th>PRICE</th>


        </tr>
        </thead>
        <tbody>
        {% for item in items %}
        <tr>
            <td class="service">{{ item.tasks.titre }}</td>
            <td class="desc">{{ item.titre }}</td>
            <td class="unit">80.00DT</td>
            <td></td>


        </tr>
     {% endfor %}
        <tr>
            <td colspan="3" class="grand total">GRAND TOTAL</td>
            <td class="grand total">{{ items|length *80 }} &nbsp; DT</td>
        </tr>
        </tbody>
    </table>
    <div id="notices">
        <div>NOTICE:</div>
        <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>
    </div>
</main>
<footer>
    Invoice was created on a computer and is valid without the signature and seal.
</footer>
</body>

templates/item/edit.html.twig
{% block body %}


    {{ include('item/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_item_index') }}">back to list</a>

{% endblock %}

templates/item/index.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    {% if task.titre is defined %}
    <h3><i class="fas fa-tasks"></i> {{ task.titre }}</h3>
    {%  endif %}
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>Titre</th>
            <th>temps</th>
            <th>status</th>
            <th>photo</th>
            <th>editer</th>
            <th>supprimer</th>

        </tr>

        </thead>
        <tbody>
        {% if items is null %}
        <h1> vous n'avez pas des items assignés !</h1>
        {%  else %}
        {% for item in items %}
        <tr>
            <td>{{ item.titre }}</td>
            <td> {{ item.time|date('H:i:s') }}</td>
            {% if item.iscomplete %}
            <td style="color: green">complété</td>
            {% else %}
                <td style="color: red ">non complété</td>
                {% endif %}
            {%  if item.photo  is null%}
                <td style="color: orangered">pas de preuve</td>
            {%  else %}
            <td>         <a href="{{ asset('uploads/users/'~ item.photo)}}" target="_blank">    <button class="btn-success">voir preuve</button>          </a>
         {#   <td><button type="button" class="btn btn-success" data-mdb-toggle="modal" data-mdb-target="#exampleModal"> voir preuve
                </button></td>#}
                {% endif %}
                <td><a href="{{ path('app_item_edit', {'id': item.id}) }}">  <button class="btn-sm "><i class="fas fa-edit"></i></button></a>
                </td>
            <td>  <form method="post" action="{{ path('app_item_delete', {'id': item.id}) }}" onsubmit="return confirm('est ce que vous étes sure de vouloir supprimer le Task?');">
                    <input   type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
                     <button class=" btn-sm "><i class="fas fa-trash fa-1x"></i></button>
                </form></td>

        </tr>





            <!-- Modal of new task -->
{#
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">{{ item.titre }}</h5>
                            <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">

                            <img src="{{ asset('uploads/ImagesItems/'~ item.photo) }}"  >
                            <div class="modal-footer">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
#}



            <!-- end modal new task -->



            </div><!-- /.row -->

        {% endfor %}
        {%  endif %}

        </tfoot>
    </table>



    <h1 style="color: white">white</h1>
    <h1 style="color: white">white</h1>
    <h1 style="color: white">white</h1>
    <h1 style="color: white">white</h1>
    <h1 style="color: white">white</h1>
    <h1 style="color: white">white</h1>


{%  endblock %}

templates/item/index_admin.html.twig
{% extends 'admin.html.twig' %}

{% block body %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <table class="table  table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">titre</th>
            <th scope="col">heure</th>
            <th scope="col">status</th>
            <th scope="col">photo</th>
            <th scope="col">editer</th>

            <th scope="col">supprimer</th>

        </tr>
        </thead>
        <tbody>
        {% for item in items %}
        <tr>

                <th scope="row "> {{ item.id }}</th>
                <td class="font-italic "> {{ item.titre}}</td>
            {% if item.iscomplete  %}
                <td style="color: #005ad0">compléte</td>
            {% else %}
                <td style="color: #d0003e">non compléte</td>
            {% endif %}

                <td>{{ item.time|date('H:i:s') }}</td>
            {%  if item.photo  is null%}
            <td style="color: orangered">pas de preuve</td>
            {%  else %}
            <td>         <a href="{{ asset('uploads/ImagesItems/'~ item.photo)}}" target="_blank">    <button class="btn-dark">voir preuve</button>          </a>

                {% endif %}



                {% endfor %}

            </tr>

        </tbody>
    </table>


{%  endblock %}

templates/item/new.html.twig
{#
{% extends 'base.html.twig' %}
#}


{% block body %}

    {{ include('item/_form.html.twig') }}

    <a href="{{ path('app_item_index') }}">back to list</a>
{% endblock %}

templates/item/show.html.twig
{#
{% extends 'base.html.twig' %}

{% block title %}Item{% endblock %}

{% block body %}
    <h1>Item</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ item.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ item.titre }}</td>
            </tr>
            <tr>
                <th>Time</th>
                <td>{{ item.time ? item.time|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Is_complete</th>
                <td>{{ item.isComplete ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_item_index') }}">back to list</a>

    <a href="{{ path('app_item_edit', {'id': item.id}) }}">edit</a>

    {{ include('item/_delete_form.html.twig') }}
{% endblock %}
#}